### PR TITLE
Fix animated chiclet handling

### LINKED ISSUE #695: Vanilla Video targets the dashboard carousel
image

### PR DESCRIPTION
**Pull request by marcustyphoon**
"Chiclet" doesn't look like a word anymore.

#### User-facing changes
Two fixes to the handling of the animated "chiclet" elements in the dashboard (ex-"you're caught up!") carousel and https://www.tumblr.com/timeline/trending:
- Prevents Vanilla Videos from messing with chiclet appearance
- Fixes AccessKit's de-animation function

#### Technical explanation
Vanilla Video: I don't know if there are videos that should be included that do not use the `videoPlayer` class.

#### Issues this closes
resolves #695 (though it mentions more work that is a good idea)
addresses the core issue in #696, but does not implement its suggestion of improved functionality (could update that issue or close it and create a new enhancement issue)

### CODE REVIEW

File: src/scripts/vanilla_video.js [hunk 1]
```diff
@@ -37,7 +38,7 @@ export const onStorageChanged = async function (changes, areaName) {
 
 export const main = async function () {
   ({ defaultVolume } = await getPreferences('vanilla_video'));
-  pageModifications.register(`video:not([src], .${vanillaVideoClass})`, cloneVideoElements);
+  pageModifications.register(`${keyToCss('videoPlayer')} video:not([src], .${vanillaVideoClass})`, cloneVideoElements);
```
Comment (AprilSylph) [inline src/scripts/vanilla_video.js:41]: targeting `videoPlayer` parents makes the `[src]` exclusion unnecessary here

```suggestion
  pageModifications.register(`${keyToCss('videoPlayer')} video:not(.${vanillaVideoClass})`, cloneVideoElements);
```

**Review by AprilSylph — CHANGES_REQUESTED** [review]

**Review by AprilSylph — APPROVED** [review]
