### PR TITLE
Trim Reblogs: Fix silent failure if original root post is deleted

### LINKED ISSUE #563: Trim Reblogs: Silent failure if original root post is deleted
### Platform

MacOS 10.14.6 x86

### Browser

Edge 100.0.1185.44

### Addon version

0.19.3

### Details

Pressing the trim reblogs button on a reblog chain whose original root post has been deleted appears to do nothing; the apiFetch to check `shouldOpenInLegacy` 404s and the rejected promise kills the callback without anything else happening like notifying the user.

(Apologies if I have some details wrong here; reporting the bug before I forget. May test more carefully later.)

### PR DESCRIPTION
**Pull request by marcustyphoon**
I feel like our understanding of when trim reblogs does and doesn't work must be incomplete. Nevertheless, this seems like an improvement.

#### User-facing changes
- Trim Reblogs will warn the user but allow them to continue instead of silently failing if the root post cannot be retrieved to determine if the thread in question is legacy.

#### Technical explanation
Maybe `.catch(() => ({ response: {} }))` is more elegant? I find it a bit hard to proofread.

#### Issues this closes
resolves #563

### CODE REVIEW

File: src/scripts/trim_reblogs.js [hunk 1]
```diff
@@ -25,12 +25,17 @@ const onButtonClicked = async function ({ currentTarget }) {
     rebloggedRootId
   } = await timelineObject(postElement);
 
+  let unsureOfLegacyStatus = true;
```
Comment (AprilSylph) [inline src/scripts/trim_reblogs.js:28]:
```suggestion
  let unsureOfLegacyStatus;
```

File: src/scripts/trim_reblogs.js [hunk 2]
```diff
@@ -25,12 +25,17 @@ const onButtonClicked = async function ({ currentTarget }) {
...
-      return;
-    }
+    try {
+      const { response: { shouldOpenInLegacy } } = await apiFetch(`/v2/blog/${rebloggedRootUuid}/posts/${rebloggedRootId}`);
+      if (shouldOpenInLegacy) {
+        notify('Legacy posts cannot be trimmed.');
+        return;
+      }
+      unsureOfLegacyStatus = false;
+    } catch (e) {}
```
Comment (AprilSylph) [inline src/scripts/trim_reblogs.js:38]:
```suggestion
    } catch (exception) {
      unsureOfLegacyStatus = true;
    }
```

**Review by AprilSylph — CHANGES_REQUESTED** [review]
I think the most elegant thing is to make what we're doing, in the event of `apiFetch` rejecting, more explicit

**Review by AprilSylph — APPROVED** [review]
