### PR TITLE
Themed Posts: Function in Communities

### LINKED ISSUE #1494: Restore Attribution tweak breaks Communities blog links
### Platform

MacOS 14.4.1 arm64

### Browser

Chrome 125.0.6422.77

### Addon version

master

### Details

As per: https://www.tumblr.com/communities/communities-feedback/post/752845459562856448/bug-report-clicking-on-a-posters-username-in-a

The "restore attribution links" tweak causes a broken author link in Tumblr Communities.

### PR DESCRIPTION
**Pull request by marcustyphoon**
### Description

Related: #1441

As noted in the first linked issue, posts can have not only the single blog that "owns" them, but can also have a secondary blog associated with them: either the submitting blog if the post is a submission, the author blog if the post is on a group blog with the "show author portraits" setting enabled, or the author blog if the post is part of Tumblr Communities.

Notably, in the third case, the Tumblr UI reverses how these two fields affect how a post is rendered (the community owns the post, but the post looks like the "authorBlog" owns it).

Themed Posts' rendering should be consistent with how a post looks, so this overrides the field it queries to determine post color only in the case of Communities posts.

(I had changes to other scripts in this PR but none of them wound up being entirely correct.)

### Testing steps

- Confirm that Themed Posts functions normally outside of Communities.
- Confirm that Themed Posts colors posts in Communities with the author's blog color.

### CODE REVIEW

**Comment by marcustyphoon** [comment]
Notes:
- Mutual checker works with no changes on Communities pages, but it's firing API requests unnecessarily rather than parsing `authorBlog` when `blog` doesn't match. The code change to improve this is somewhat awkward, though.
- I can't test Quick Tags on Communities.
- I can't test NotificationBlock on Communities (blockPostFilter may be wrong, and the apiFetch to check if the post is muted probably crashes if the button actually is clickable? most likely fine though)

File: src/scripts/themed_posts.js [hunk 1]
```diff
@@ -30,7 +30,8 @@ const processPosts = async function (postElements) {
   filterPostElements(postElements, { includeFiltered: true }).forEach(async postElement => {
     if (postElement.matches(blogViewSelector) && !enableOnPeepr) return;
 
-    const { blog, trail = [], content } = await timelineObject(postElement);
+    const { blog: owningBlog, authorBlog, trail = [], content, community } = await timelineObject(postElement);
+    const blog = community ? authorBlog : owningBlog;
```
Comment (AprilSylph) [inline src/scripts/themed_posts.js:34]: not much of a fan of renaming `blog` in the destructure here. how about...

```suggestion
    const { blog, authorBlog, trail = [], content, community } = await timelineObject(postElement);
    const visibleBlog = community ? authorBlog : blog;
```

File: src/scripts/themed_posts.js [hunk 2]
```diff
@@ -30,7 +30,8 @@ const processPosts = async function (postElements) {
...
 
     const blogData = [
       blog,
```
Comment (AprilSylph) [inline src/scripts/themed_posts.js:37]:
```suggestion
      visibleBlog,
```

**Review by AprilSylph — APPROVED** [review]
