### PR TITLE
Scroll to Bottom: Stop at bottom + Fix button color

### LINKED ISSUE #712: Scroll to Bottom: Button does not change color
### Platform

MacOS 10.14.6 x86

### Browser

Edge 104.0.1293.54

### Addon version

v0.20.7

### Details

The Scroll to Bottom button does not turn yellow when active.

Almost certainly the same issue and fix as #644.

### PR DESCRIPTION
**Pull request by marcustyphoon**
#### User-facing changes
- Scroll to bottom's button correctly turns yellow when active.
- Scroll to bottom correctly stops when it gets to the "bottom" of the page.
- ~~Scroll to bottom stops if you open the blog view modal while scrolling (otherwise it would continue in the background; #488 was not implemented)~~
- Minor visual fix on non-glass /blog/view pages, which have a visible scroll to top button but no visible scroll to bottom button (as per reasoning in #488)

Note: the script does not work on https://www.tumblr.com/following before or after this PR due to Tumblr quirks (there isn't a persistent loading indicator on the page and it looks to me like the site doesn't change behavior when you get to the end of the list)

#### Technical explanation
n/a

#### Issues this closes
resolves #712
addresses only the comment in #619 ("scrolling doesn't stop when there are no more posts on the page"); do not close this issue

### CODE REVIEW

**Comment by marcustyphoon** [comment]
- [ ] call stopScrolling on navigation somehow

Man, I wish #453 was less... hacky.

File: src/scripts/scroll_to_bottom.js [hunk 1]
```diff
@@ -30,7 +30,9 @@ const scrollToBottom = () => {
   const loaders = [...document.querySelectorAll(loaderSelector)]
     .filter(element => element.matches(blogViewSelector) === false);
 
-  if (loaders.length === 0) {
+  const glassContainerOpen = document.getElementById('glass-container')?.hasChildNodes();
```
Comment (AprilSylph) [inline src/scripts/scroll_to_bottom.js:33]: Is this reliable again? Last I knew, the glass container doesn't have an ID at all if the first route has glass (e.g, `/new/text`), hence the usage of `[role="dialog"]` glass checks everywhere.

Comment (marcustyphoon) [reply src/scripts/scroll_to_bottom.js:33]: a) That is a good question! I didn't see any instances where it didn't on a quick check, but I'm not sure exactly where to look. However:
b) I just noticed this makes scroll to bottom stop if you accidentally mouse over a blog avatar.

Uh. Oops.

File: src/scripts/scroll_to_bottom.js [hunk 2]
```diff
@@ -1,27 +1,36 @@
...
-import { buildStyle } from '../util/interface.js';
+import { blogViewSelector, buildStyle } from '../util/interface.js';
 
 const scrollToBottomButtonId = 'xkit-scroll-to-bottom-button';
 $(`[id="${scrollToBottomButtonId}"]`).remove();
+const activeClass = 'xkit-scroll-to-bottom-active';
 
-const knightRiderLoaderSelector = `main ${keyToCss('loader')} ${keyToCss('knightRiderLoader')}`;
+const loaderSelector = `
+${keyToCss('timeline', 'blogRows')} > ${keyToCss('loader')},
```
Comment (AprilSylph) [inline src/scripts/scroll_to_bottom.js:11]: What are `blogRows`?

Comment (AprilSylph) [reply src/scripts/scroll_to_bottom.js:11]: Oh wait, I see, it's follower/following lists. I guess those are rows of blogs.

File: src/scripts/scroll_to_bottom.js [hunk 3]
```diff
@@ -1,27 +1,36 @@
...
 
 let scrollToBottomButton;
-let scrollToBottomIcon;
 let active = false;
 
 const styleElement = buildStyle(`
 ${keyToCss('isPeeprShowing')} #${scrollToBottomButtonId} {
-  opacity: 0;
-  pointer-events: none;
+  display: none;
```
Comment (AprilSylph) [inline src/scripts/scroll_to_bottom.js:20]: The hiding CSS was the way it was for a reason; it allows the scroll to bottom button to fade out/in with the scroll to top button when peepr is opened/closed.
```suggestion
  opacity: 0;
  pointer-events: none;
```

**Review by AprilSylph — CHANGES_REQUESTED** [review]

File: src/scripts/scroll_to_bottom.js (hunk 3 above)
Comment (marcustyphoon) [reply src/scripts/scroll_to_bottom.js:20]: Hmmm. Makes sense; I guess non-modal blog view will need a different solution.

Comment (marcustyphoon) [reply src/scripts/scroll_to_bottom.js]: Almost works, but it glitches briefly when you scroll up in non modal blog view. Oh well, really not important.

```diff
  ${keyToCss('isPeeprShowing')} #${scrollToBottomButtonId} {
    opacity: 0;
    pointer-events: none;
  }

+ ${keyToCss('isPeeprShowing')} button:not(${keyToCss('hidden')}) + #${scrollToBottomButtonId} {
+   display: none;
+ }
```

**Review by AprilSylph — APPROVED** [review]
Shame to merge this without a fix for the non-modal blog view issue, but it's minor enough (doesn't impair use) and the other fixes are more important.

Also, I was going to say this fixes #619 for me, but I only tested it going from my drafts to the dashboard. If going between drafts and the queue still doesn't deactivate scroll to bottom by itself, I don't think it ever did, and I'd be tempted to classify that behaviour as working as intended.

**Comment by marcustyphoon** [comment]
Interesting; I swore that going from drafts to dashboard wasn't stopping it for me, but it certainly is now. It's triggering the "no loader" code; it looks like `checkForButtonRemoved` isn't doing much of anything at the moment.

Anyway, yes, I think "I clicked a UI element while scroll to bottom was actively making my page jump around" having nonobvious behavior doesn't even really count as a bug almost regardless of what that behavior is, because... you know, why, and what were you expecting :D

I do like the currently unimplemented behavior of "clicking the Tumblr logo stops scroll to bottom on the dashboard" though.
