### PR TITLE
fix(Hide Avatars): update feature for new post header

### LINKED ISSUE #1756: Hide Avatars doesn't apply to community posts/new post header
### Platform

iPad simulator

### Browser

Safari 18.1

### Addon version

v1.0.8

### Details

Hide Avatars doesn't apply to the new post header used in community posts.

### PR DESCRIPTION
**Pull request by AprilSylph**
### Description

- Fixes #1756

Before | After
-|-
Screen Shot 2025-08-07 at 13 56 59 | Screen Shot 2025-08-07 at 13 57 18

Hide Avatars should now hide all avatars from inputted blogs, including in the new post header and other non-post places like blog cards and Peepr.

I elected to use `filter: blur(64px);` over `display: none;` so that avatars now leave behind a slight tint instead of being hidden completely, which means the overall shape of post headers is now retained.

Given the usage of the `translate` utility to find avatar images via ARIA labels, I checked to make sure this fix applies regardless of the current user's language; it seems like there are no issues:

<details><summary>Screenshots grid</summary>

Screen Shot 2025-08-07 at 13 57 18 | Screen Shot 2025-08-07 at 14 04 12 | Screen Shot 2025-08-07 at 14 04 17
-- | -- | --
Screen Shot 2025-08-07 at 14 04 21 | Screen Shot 2025-08-07 at 14 04 25 | Screen Shot 2025-08-07 at 14 04 28
Screen Shot 2025-08-07 at 14 04 31 | Screen Shot 2025-08-07 at 14 04 34 | Screen Shot 2025-08-07 at 14 04 38
Screen Shot 2025-08-07 at 14 04 41 | Screen Shot 2025-08-07 at 14 04 44 | Screen Shot 2025-08-07 at 14 04 48
Screen Shot 2025-08-07 at 14 04 51 | Screen Shot 2025-08-07 at 14 05 05 | Screen Shot 2025-08-07 at 14 05 08
Screen Shot 2025-08-07 at 14 05 12 | Screen Shot 2025-08-07 at 14 05 16 | Screen Shot 2025-08-07 at 14 05 20

</details>

### Testing steps

1. Load the modified addon
2. Restore this configuration:
      ```json
      {
        "anti_capitalism.preferences.includeBlazed": true,
        "enabledScripts": [
          "anti_capitalism",
          "hide_avatars"
        ],
        "hide_avatars.preferences.hiddenAvatars": "cheezbot, quelmdn, cashoffers65",
        "specialAccess": []
      }
      ```
3. Go to https://www.tumblr.com/cheezbot/791125843876429824
    - [ ] **Expected result**: `cheezbot`'s avatar is hidden in the post header
    - [ ] **Expected result**: 🆕 `cheezbot`'s avatar is hidden in the right rail
    - [ ] **Expected result**: `quelmdn`'s avatar is hidden in the reblog header
    - [ ] **Expected result**: `cashoffers65`'s avatar is hidden in the post notes

### CODE REVIEW

**Comment by marcustyphoon** [comment]
This doesn't affect the "facepile" thingy at the bottom of community posts but eh, that's kind of fine, right.

File: src/features/hide_avatars/index.js [hunk 1]
```diff
@@ -9,6 +9,6 @@ export const main = async function () {
 
   styleElement.textContent = hiddenAvatars
     .split(',')
-    .map(username => `[title="${username.trim()}"] img[alt="${translate('Avatar')}"] { display: none; }`)
+    .map(blogname => `a[href="/${blogname.trim()}"] img[alt="${translate('Avatar')}"] { filter: blur(64px); }`)
```
Comment (marcustyphoon) [inline src/features/hide_avatars/index.js]:
```suggestion
    .map(blogname => `a:is([href="/${blogname.trim()}"], [title="${blogname.trim()}"]) img[alt="${translate('Avatar')}"] { filter: blur(64px); }`)
```

Currently doesn't appear to work on the likes list, since it links—for whatever reason—to blog network. Combining both selectors would work. (Targeting blog network urls is probably bad because of custom domains, I assume, though maybe there's actually a redirect and it doesn't matter?)

Comment (AprilSylph) [reply src/features/hide_avatars/index.js]: Hmm, I would love to be sure about the custom domain behaviour, but I can't think of any blogs with custom domains that have their likes public (thus making it easy to find a like note from them on a post).

Comment (marcustyphoon) [reply src/features/hide_avatars/index.js]: "That's fine, I'll just make—oh. Hm."

Comment (marcustyphoon) [reply src/features/hide_avatars/index.js]: https://www.tumblr.com/april/790946367972556800/lascapigliata-tony-soprano-privacy-rights is liked by user crwncks and has a link that looks like this: `<a href="https://kalecchi.com/" title="crwncks" rel="noopener" target="_blank" class="BSUG4" role="link" tabindex="0">`

q: how?
a: 

```css
a[href$=".tumblr.com/"] img[alt="Avatar"] {
  outline: 5px dotted red;
  outline-offset: -3px;
}

a img[alt="Avatar"] {
  outline: 5px solid green;
  outline-offset: -3px;
}
```

Comment (AprilSylph) [reply src/features/hide_avatars/index.js]: Ah, cool!

**Review by marcustyphoon — APPROVED** [review]

**Comment by marcustyphoon** [comment]
There does appear to be a separate translation entry for `The avatar for a community\u0004Avatar`, but a) I don't think it's used and b) it's currently the same as the `Avatar` string. Oh: also, this feature doesn't really work on communities anyway, currently, so whatever.
