### PR TITLE
Trim Reblogs: More accurate legacy post detection

### LINKED ISSUE #909: Trim Reblogs: Excessive space before unsure-of-legacy text
### Platform

MacOS 10.15.7 x86

### Browser

Ungoogled Chromium v108.0.5359.94

### Addon version

master

### Details

image

### LINKED ISSUE #956: Trim Reblogs: Inaccurate legacy post detection on mobile-edited posts
### Platform

MacOS 10.15.7 x86

### Browser

Ungoogled Chromium v109.0.5414.119

### Addon version

master

### Details

As discussed in https://github.com/tumblr/docs/issues/96, the current shouldOpenInLegacy method of detecting legacy posts is inaccurate in certain cases.

This has led to well-intentioned PSAs spreading that editing a legacy thread on mobile will make the thread able to be trimmed without bugs using Trim Reblogs when it previously would not have. Unless I am testing incorrectly, this is not true.

If I'm right about this, and if you wouldn't mind, @AprilSylph, I would like to request that the linked PR be at the top of the PR review order.

### PR DESCRIPTION
**Pull request by marcustyphoon**
### Description

Thanks to Cyle's change documented in https://github.com/tumblr/docs/issues/96, the `isBlocksPostFormat` field can now be used to determine if a thread's root post is legacy without an API request and without relying on the root post still existing. This takes advantage of said field.

Resolves #909, as the element in question no longer exists.

Resolves #956.

### Testing steps

Attempt to trim reblogs on the different categories of posts (root-legacy beta-reblog, etc).

### CODE REVIEW

File: src/scripts/trim_reblogs.js [hunk 1]
```diff
@@ -30,35 +30,24 @@ const onButtonClicked = async function ({ currentTarget: controlButton }) {
...
+      showModal({
+        title: 'Note: Legacy post',
+        message: [
+          'The root post of this thread was originally created with the legacy post editor.',
+          '\n\n',
+          'On these threads, Trim Reblogs may work normally, have no effect, or require a repeat of the trim action to completely remove the desired trail items.'
+        ],
+        buttons: [
+          modalCancelButton,
+          dom('button', { class: 'blue' }, { click: () => resolve() }, ['Continue'])
```
Comment (AprilSylph) [inline src/scripts/trim_reblogs.js:47]:
```suggestion
          dom('button', { class: 'blue' }, { click: resolve }, ['Continue'])
```

**Review by AprilSylph — APPROVED** [review]
