### PR TITLE
NotificationBlock: Fix menu item missing on non-editable posts

### LINKED ISSUE #627: NotificationBlock can't be used on Blazed posts
### Platform

macOS Big Sur 11.6.5

### Browser

Firefox

### Addon version

v0.19.6

### Details

I can't block notifications. When I press the meatball thing, I only see [this](https://64.media.tumblr.com/2898e3f0b959eed44c63f86b31d2a0d4/690cc01f5c73a6db-75/s540x810/903236bca8b0a7b2bcbf917220de3ac9d3bb2f33.png). I've for sure got it turned on as you can see [here](https://64.media.tumblr.com/a64d0fb739951858978092c62af0f802/690cc01f5c73a6db-db/s1280x1920/714095fe5509fad2a6a57f1a3b4f0dc192ec64e6.png) but it's still giving me notifications for this post in my activity tabs. Thank you please help.

### PR DESCRIPTION
**Pull request by marcustyphoon**
#### User-facing changes
- NotificationBlock menu items appear on non-editable posts

#### Technical explanation
The notificationblock menu item appears on any post from any of the user's blogs, regardless of whether the user has edit access to that post.

This makes sense for blazed posts the user has made, as well as group blog posts that the user didn't make and can't edit, as the user can still see notifications on those.

#### Issues this closes
resolves #627
(for real this time)

### CODE REVIEW

**Comment by marcustyphoon** [comment]
Hm, you definitely are right that adding the UI to the notifications themselves solves a lot of weirdness.

I just noticed that it would - in theory - make sense to also have these buttons on any post containing one of your blogs in the reblog chain, in a way. After all, if I reblog user A's post, and I receive a notification that user B has reblogged my reblog, and I click that notification... it opens user B's blog. In that case, I have open a post which I might want to block future similar notifications from, in which I am neither the current post author nor the root post author.

**Comment by marcustyphoon** [comment]
`blog.name` is equivalent to `blogName`, right?

**Comment by AprilSylph** [comment]
I think `blogName` and `blog.name` should be the same, yeah.

File: src/scripts/notificationblock.js [hunk 1]
```diff
@@ -79,9 +80,12 @@ const onButtonClicked = async function ({ currentTarget }) {
...
 };
 
-const blockPostFilter = async ({ id, canEdit, rebloggedRootId }) => {
+const blockPostFilter = async ({ blogName, rebloggedRootName, rebloggedFromName, id, rebloggedRootId }) => {
   const rootId = rebloggedRootId || id;
-  return canEdit && blockedPostTargetIDs.includes(rootId) === false;
+  const yourOriginalPost = userBlogNames.includes(rebloggedRootName);
+  const yourReblog = userBlogNames.includes(blogName) || userBlogNames.includes(rebloggedFromName);
+
+  return (yourOriginalPost || yourReblog) && blockedPostTargetIDs.includes(rootId) === false;
```
Comment (AprilSylph) [inline src/scripts/notificationblock.js:88]: These names aren't strictly accurate... `rebloggedRootName` will be undefined when viewing _any_ original post, which means all original posts when viewing your own blog would be counted as `yourReblog` rather than `yourOriginalPost`.

What's being tested for *is* correct though, so let's just combine the two constants.

```suggestion
  const canReceiveActivity = userBlogNames.includes(blogName) ||
    userBlogNames.includes(rebloggedFromName) ||
    userBlogNames.includes(rebloggedRootName);

  return canReceiveActivity && blockedPostTargetIDs.includes(rootId) === false;
```

**Review by AprilSylph — CHANGES_REQUESTED** [review]

File: src/scripts/notificationblock.js (hunk 1 above)
Comment (marcustyphoon) [reply src/scripts/notificationblock.js:88]: Oh, right! Whoops. Sometimes I think I need to just write documentation for the timelineObject fields for myself as if they were official API endpoints :D

**Review by AprilSylph — APPROVED** [review]
