### PR TITLE
Footer redesign revert tweak: New implementation

### LINKED ISSUE #553: Old Footer Change not Working
### Platform

macOS 11.6.5

### Browser

Chrome Version 100.0.4896.88

### Addon version

v0.19.2

### Details

The footer change to the original one is back to the current update. This only happened a couple of minutes ago, and worked fine during the rest of the day. Restarting Tumblr did not help. I have the "tweaks" part on, along with "attempt to revert the post footer design" checked off.

### PR DESCRIPTION
**Pull request by marcustyphoon**
I haven't done what I think of as a  "self-review" of this yet, per se. Seems to work though.

#### User-facing changes
- Fixes the footer redesign revert tweak not working after Staff removed the old footer CSS.

#### Technical explanation
Primarily based on the comment in #413. This removes the manipulation of the `footerRedesign` class, which no longer exists, implementing the old footer css explicitly.

Staff added a `footerRow` element in between the footer element and its children, necessitating a few tweaks.

The functionality on #459 is done how I personally think is the most clear: always putting a bottom ~~margin~~ *padding* on the footer; never putting a top margin on the `postActivityWrapper`.

#### Issues this closes
#553

### CODE REVIEW

File: src/scripts/tweaks/footer_unredesign.js [hunk 1]
```diff
@@ -1,32 +1,29 @@
...
-}
-
-article footer > ${keyToCss('noteCount')} {
+article footer ${keyToCss('footerRow')} {
+  display: flex;
+  justify-content: space-between;
   align-items: center;
-  gap: var(--post-padding);
+  flex-wrap: wrap;
+  margin-bottom: 12px;
```
Comment (AprilSylph) [inline src/scripts/tweaks/footer_unredesign.js:12]:
```suggestion
  padding-bottom: 12px;
```

**Review by AprilSylph — CHANGES_REQUESTED** [review]
Before | After
-------|------
image | image

File: src/scripts/tweaks/footer_unredesign.js (hunk 1 above)
Comment (marcustyphoon) [reply src/scripts/tweaks/footer_unredesign.js:12]: Whoops! 👍

**Review by AprilSylph — APPROVED** [review]
